header := "# Generated by just build — do not edit manually."
join := "awk 'FNR==1 && NR>1{print \"\"}1'"
shared := "Shared/common.sh"
wsl := "Shared/wsl-common.sh"

build:
    { printf '%s\n\n' '{{ header }}'; {{ join }} {{ shared }} EndeavourOS/distro.sh; } > EndeavourOS/prepare.sh
    { printf '%s\n\n' '{{ header }}'; {{ join }} {{ shared }} {{ wsl }} Fedora/distro.sh; } > Fedora/prepare.sh
    { printf '%s\n\n' '{{ header }}'; {{ join }} {{ shared }} {{ wsl }} Ubuntu/distro.sh; } > Ubuntu/prepare.sh
