generated_notice := "\n# Generated by just build — do not edit manually."
bash_header := "#!/usr/bin/env bash" + generated_notice
dash_header := "#!/usr/bin/env dash" + generated_notice
join := "awk 'FNR==1 && NR>1{print \"\"}1'"
shared := "Shared/common.sh"
wsl := "Shared/wsl-common.sh"

build:
  { printf '%s\n\n' '{{ bash_header }}'; {{ join }} {{ shared }} EndeavourOS/distro.sh; } > EndeavourOS/prepare.sh
  { printf '%s\n\n' '{{ dash_header }}'; {{ join }} {{ shared }} {{ wsl }} Debian/distro.sh; } > Debian/prepare.sh
  { printf '%s\n\n' '{{ bash_header }}'; {{ join }} {{ shared }} {{ wsl }} Fedora/distro.sh; } > Fedora/prepare.sh
  { printf '%s\n\n' '{{ dash_header }}'; {{ join }} {{ shared }} {{ wsl }} Ubuntu/distro.sh; } > Ubuntu/prepare.sh
