# Generated by just build — do not edit manually.

FONT="JuliaMono"
# shellcheck disable=SC2034
JAVA_VER="21"

__get_gh_repo() {
  git -C "${1}" pull || git clone --depth=1 "https://github.com/${2}.git" "${1}"
}

__install_fonts() {
  local setup_dir="${1}"
  fc-list | grep -q "/${FONT}-" || {
    cp "${setup_dir}/Assets/${FONT}/"*.ttf "${HOME}/.local/share/fonts/"
    fc-cache -f
  }
}

__set_default_shell() {
  local -
  set +x
  local zsh_path
  zsh_path=$(command -v zsh)
  [ "$(getent passwd "${USER}" | cut -d: -f7)" = "${zsh_path}" ] || sudo chsh -s "${zsh_path}" "${USER}"
}

__setup_git_config() {
  local user_csv="${1}"
  local tpl_path="${2}"
  local out_path="${3}"
  local git_user_name git_user_email

  if [ ! -f "${user_csv}" ]; then
    read -rp "Enter your Git user name: " git_user_name
    read -rp "Enter your Git user email: " git_user_email
    echo "${git_user_name},${git_user_email}" > "${user_csv}"
  else
    IFS="," read -r git_user_name git_user_email < "${user_csv}"
  fi

  sed -e "s/{{GIT_USER_NAME}}/${git_user_name}/" \
    -e "s/{{GIT_USER_EMAIL}}/${git_user_email}/" \
    "${tpl_path}" > "${out_path}"
}

PKGS=(
  android-tools asciinema asciinema-agg-bin asciiquarium bat bibata-cursor-theme bind
  breeze-plymouth claude-code cmake cmatrix cowsay curlie discord dive docker docker-compose
  eza fastfetch figlet ghostty github-cli go-yq goaccess gron htop hugo
  intellij-idea-community-edition "jdk${JAVA_VER}-openjdk" jq just kora-icon-theme krabby-bin
  lolcat meson moreutils ninja openbsd-netcat pastel perl-image-exiftool plymouth plymouth-kcm
  python-pdm python-pip rclone sbctl shellcheck shfmt steam strace tcpdump telegram-desktop tmux
  tokei tree ttf-fira-code ttf-jetbrains-mono ttf-tahoma wireshark-cli wl-clipboard zsh
  zsh-autosuggestions zsh-completions zsh-syntax-highlighting
)

SETUP_DIR="${HOME}/Projects/setup"
DISTRO_NAME="EndeavourOS"
PLYMOUTH_THEME="breeze"
KEYBOARD_LAYOUT="us,il"

set -eux

system_setup() {
  __get_gh_repo "${SETUP_DIR}" gchait/setup
  sudo cp -r "${SETUP_DIR}/${DISTRO_NAME}/Etc/"* /etc
  local locale="en_IL"

  locale -a | grep -q "${locale}" || {
    sudo sed -i "s/^#\(${locale} UTF-8\)/\1/;s/^#\(en_US\.UTF-8 UTF-8\)/\1/" /etc/locale.gen
    sudo locale-gen
  }

  local locale_status
  locale_status=$(localectl status)

  grep -q "LANG=${locale}" <<< "${locale_status}" || sudo localectl set-locale \
    LANG="${locale}" LC_ADDRESS="${locale}" LC_IDENTIFICATION="${locale}" LC_MEASUREMENT="${locale}" \
    LC_MONETARY="${locale}" LC_NAME="${locale}" LC_NUMERIC="${locale}" LC_PAPER="${locale}" \
    LC_TELEPHONE="${locale}" LC_TIME="${locale}"

  grep -q "VC Keymap: il" <<< "${locale_status}" || sudo localectl set-keymap il
  grep -q "X11 Layout: ${KEYBOARD_LAYOUT}" <<< "${locale_status}" || sudo localectl set-x11-keymap "${KEYBOARD_LAYOUT}" "" "" grp:alt_shift_toggle

  yay -Syu --noconfirm
}

packages_setup() {
  # shellcheck disable=SC2046
  yay -Rns --noconfirm $(yay -Qq \
    amdvlk b43-fwcutter dialog dmraid endeavouros-konsole-colors eos-apps-info eos-log-tool \
    eos-quickstart glances haveged iwd kdeconnect kgamma konsole lib32-amdvlk libdvdcss lsscsi \
    nano nano-syntax-highlighting networkmanager-openvpn nilfs-utils ntp partitionmanager pkgfile \
    plasma-x11-session print-manager sysfsutils usb_modeswitch welcome xf86-video-ati xl2tpd \
    xorg-xinit xorg-xinput xorg-xkill xterm \
    2> /dev/null) 2> /dev/null || true

  # shellcheck disable=SC2046
  yay -Rns --noconfirm $(yay -Qdtq) 2> /dev/null || true
  yay -S --needed --noconfirm "${PKGS[@]}" 2> /dev/null

  # shellcheck disable=SC2016
  printf '#!/bin/bash\nwhile :; do POK=$(krabby random 1,3 --no-title --no-regional --no-gmax); read -r W H < <(awk "length>m{m=length} END{print m, NR}" <<< "${POK}") && (( W < 1000 && H < 15 )) && break; done; echo "${POK}"\n' |
    sudo install -m 0755 /dev/stdin /usr/local/bin/poke
}

home_setup() {
  gsettings set org.gnome.desktop.interface gtk-enable-primary-paste true
  __get_gh_repo "${HOME}/.zsh/p10k" romkatv/powerlevel10k

  cp "${SETUP_DIR}/Shared/Home/.p10k.zsh" "${HOME}"
  cp "${SETUP_DIR}/Shared/Home/.common.zsh" "${HOME}"
  cp -r "${SETUP_DIR}/${DISTRO_NAME}/Home/".[!.]* "${HOME}"
  mkdir -p "${HOME}/.local/share/fonts" "${HOME}/Drive"

  __install_fonts "${SETUP_DIR}"
  __setup_git_config \
    "${SETUP_DIR}/.user.csv" \
    "${SETUP_DIR}/Shared/.gitconfig.tpl" \
    "${HOME}/.gitconfig"

  local kate_tool="${HOME}/.config/kate/externaltools/Run%20Shell%20Script.ini"
  [ -f "${kate_tool}" ] && sed -i 's/^executable=konsole$/executable=ghostty/' "${kate_tool}"
}

services_setup() {
  docker ps 2> /dev/null || {
    sudo systemctl enable --now docker
    sudo usermod -aG docker "${USER}"
  }

  sudo firewall-cmd --zone=public --query-service=ssh && {
    sudo firewall-cmd --permanent --remove-service=ssh --zone=public
    sudo firewall-cmd --reload
  }

  sudo systemctl disable --now NetworkManager-wait-online.service
  sudo systemctl disable --now avahi-daemon.service avahi-daemon.socket

  printf '[Icon Theme]\nInherits=Bibata-Modern-Classic\n' |
    sudo tee /usr/share/icons/default/index.theme

  sudo rm -rf \
    /usr/share/kstyle/themes/qtplastique.themerc \
    /usr/share/kstyle/themes/qtwindows.themerc \
    /usr/share/kwin/decorations/kwin4_decoration_qml_plastik \
    /usr/share/sddm/themes/elarun \
    /usr/share/sddm/themes/maldives \
    /usr/share/sddm/themes/maya \
    /usr/share/themes/Emacs

  sudo sed -i '/sourceSize\.\(width\|height\): parent\.\(width\|height\)/d' \
    /usr/share/sddm/themes/eos-breeze/Background.qml

  __set_default_shell
}

__kw() { kwriteconfig6 --file "${1}" --group "${2}" --key "${3}" "${@:4}"; }
__kw2() { kwriteconfig6 --file "${1}" --group "${2}" --group "${3}" --key "${4}" "${@:5}"; }

kde_setup() {
  local -
  set +x

  __kw kwinrc Effect-overview BorderActivate 9
  __kw kwinrc NightColor Active --type bool true
  __kw kwinrc NightColor NightTemperature 2800

  __kw kwinrc Plugins shakecursorEnabled --type bool false
  __kw kwinrc Plugins translucencyEnabled --type bool true
  __kw kwinrc Plugins wobblywindowsEnabled --type bool true
  __kw kwinrc Xwayland Scale 2

  __kw kwinrc "org.kde.kdecoration2" ButtonsOnLeft ""
  __kw kwinrc "org.kde.kdecoration2" ButtonsOnRight IAX
  __kw kwinrc "org.kde.kdecoration2" ShowToolTips --type bool false

  __kw kscreenlockerrc Daemon Timeout 45
  __kw ksmserverrc General confirmLogout --type bool false
  __kw ksplashrc KSplash Engine none
  __kw ksplashrc KSplash Theme None
  __kw bluedevilglobalrc General bluetoothBlocked --type bool true

  __kw kxkbrc Layout DisplayNames ","
  __kw kxkbrc Layout LayoutList "${KEYBOARD_LAYOUT}"
  __kw kxkbrc Layout Use --type bool true
  __kw kxkbrc Layout VariantList ","

  __kw kdeglobals General AccentColor 85,170,255
  __kw kdeglobals General TerminalApplication ghostty
  __kw kdeglobals General TerminalService com.mitchellh.ghostty.desktop
  __kw kdeglobals Icons Theme kora

  __kw2 powerdevilrc AC Display DimDisplayIdleTimeoutSec -- -1
  __kw2 powerdevilrc AC Display DimDisplayWhenIdle --type bool false
  __kw2 powerdevilrc AC Display TurnOffDisplayIdleTimeoutSec 1800
  __kw2 powerdevilrc AC SuspendAndShutdown AutoSuspendIdleTimeoutSec 3600
  __kw2 powerdevilrc AC SuspendAndShutdown PowerButtonAction 8
}

boot_setup() {
  local efi="/efi"
  local quiet_params="quiet loglevel=3 rd.udev.log_level=3 vt.global_cursor_default=0 splash"
  local breeze_script="/usr/share/plymouth/themes/breeze/breeze.script"

  sudo test -f "${efi}/loader/loader.conf" && {
    sudo sed -i "s/^timeout.*/timeout 0/" "${efi}/loader/loader.conf"
    sudo grep -q "^editor" "${efi}/loader/loader.conf" ||
      printf 'editor no\n' | sudo tee -a "${efi}/loader/loader.conf" > /dev/null
  }

  sudo sed -i "1{/quiet/!s/$/ ${quiet_params}/}" /etc/kernel/cmdline

  sudo find "${efi}/loader/entries" -maxdepth 1 -name "*.conf" ! -name "*-fallback.conf" 2> /dev/null |
    while read -r entry; do
      sudo sed -i "/quiet/!{/^options /s/$/ ${quiet_params}/}" "${entry}"
    done

  { grep -q "^Theme=${PLYMOUTH_THEME}$" /etc/plymouth/plymouthd.conf 2> /dev/null &&
    sudo grep -q 'title\.text = ""' "${breeze_script}" 2> /dev/null; } || {
    sudo plymouth-set-default-theme "${PLYMOUTH_THEME}"
    sudo sed -i 's/global\.title\.text = ".*"/global.title.text = ""/' "${breeze_script}"
    sudo dracut -q --force
  }
}

{
  system_setup
  packages_setup
  home_setup
  services_setup
  kde_setup
  boot_setup
} > /dev/null
