[Autologin]
Relogin=false
Session=plasma
User=

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=eos-breeze
CursorSize=48
CursorTheme=Bibata-Modern-Classic
Font=Noto Sans,10,-1,0,400,0,0,0,0,0,0,0,0,0,0,1

[Users]
MaximumUid=60513
MinimumUid=1000
