# Generated by just build — do not edit manually.

FONT="JuliaMono"
# shellcheck disable=SC2034
JAVA_VER="21"

set -eux

__get_gh_repo() {
  git -C "${1}" pull || git clone --depth=1 "https://github.com/${2}.git" "${1}"
}

__install_fonts() {
  local setup_dir="${1}"
  fc-list | grep -q "/${FONT}-" || {
    cp "${setup_dir}/Assets/${FONT}/"*.ttf "${HOME}/.local/share/fonts/"
    fc-cache -f
  }
}

__setup_git_config() {
  local user_csv="${1}"
  local tpl_path="${2}"
  local out_path="${3}"

  if [ ! -f "${user_csv}" ]; then
    read -rp "Enter your Git user name: " git_user_name
    read -rp "Enter your Git user email: " git_user_email
    echo "${git_user_name},${git_user_email}" > "${user_csv}"
  else
    IFS="," read -r git_user_name git_user_email < "${user_csv}"
  fi

  sed -e "s/{{GIT_USER_NAME}}/${git_user_name}/" \
    -e "s/{{GIT_USER_EMAIL}}/${git_user_email}/" \
    "${tpl_path}" > "${out_path}"
}

SETUP_DIR="${HOME}/setup"
# shellcheck disable=SC2034
ALT_JAVA_VER="17"
# shellcheck disable=SC2034
USER_PIP_PKGS=(black boto3 construct dep-logic docker-squash pandas pdm pdm-bump pyyaml)

docker_setup() {
  docker ps 2> /dev/null || {
    echo '{"default-address-pools":[{"base":"10.2.0.0/16","size":24}]}' |
      sudo tee /etc/docker/daemon.json

    sudo systemctl enable --now docker
    sudo usermod -aG docker "${USER}"
  }
}

home_setup() {
  __get_gh_repo "${HOME}/.zsh/complete" zsh-users/zsh-completions &
  __get_gh_repo "${HOME}/.zsh/highlight" zsh-users/zsh-syntax-highlighting &
  __get_gh_repo "${HOME}/.zsh/suggest" zsh-users/zsh-autosuggestions &
  __get_gh_repo "${HOME}/.zsh/p10k" romkatv/powerlevel10k &
  wait

  cp -r "${SETUP_DIR}/Shared/Home/".* "${HOME}"
  mkdir -p "${HOME}/Projects" "${HOME}/.local/share/fonts"

  __install_fonts "${SETUP_DIR}"
  __setup_git_config \
    "${SETUP_DIR}/.user.csv" \
    "${SETUP_DIR}/Shared/.gitconfig.tpl" \
    "${HOME}/.gitconfig"
}

BOOTSTRAP_APT_PKGS=(ca-certificates curl git gnupg)

APT_PKGS=(
  adwaita-icon-theme asciinema bat build-essential cmatrix docker.io docker-buildx docker-compose-v2
  dnsutils eza fd-find figlet golang-go gron helm htop hugo iproute2 iptables jq just libasound2-dev
  libasound2t64 libatk1.0-0 libcups2t64 libgbm1 libgdk-pixbuf2.0-dev libgtk-3-0t64 libgtk-3-dev
  libncurses-dev libnss3-dev libpango-1.0-0 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxi6
  libxrandr2 libxss-dev libxss1 libxtst6 lolcat make maven moreutils ncat openssl packer python3-pip
  qemu-user-static openssh-client python3-dev ripgrep shfmt symlinks tar terraform tree vim wget
  x11-xserver-utils yq zip zsh
)

DISTRO_NAME="Ubuntu"
export DEBIAN_FRONTEND=noninteractive

system_setup() {
  sudo apt-get update -y
  sudo apt-get install -y "${BOOTSTRAP_APT_PKGS[@]}" 2> /dev/null

  __get_gh_repo "${SETUP_DIR}" gchait/setup
  sudo cp -r "${SETUP_DIR}/Shared/Etc/"* /etc
  sudo cp -r "${SETUP_DIR}/${DISTRO_NAME}/Etc/"* /etc

  local arch codename
  arch=$(dpkg --print-architecture)
  codename=$(grep VERSION_CODENAME /etc/os-release | cut -d= -f2)

  sudo install -m 0755 -d /etc/apt/keyrings

  curl -fsSL https://apt.releases.hashicorp.com/gpg |
    sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  echo "deb [arch=${arch} signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com ${codename} main" |
    sudo tee /etc/apt/sources.list.d/hashicorp.list > /dev/null

  curl -fsSL https://baltocdn.com/helm/signing.asc |
    sudo gpg --dearmor -o /usr/share/keyrings/helm.gpg
  echo "deb [arch=${arch} signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" |
    sudo tee /etc/apt/sources.list.d/helm.list > /dev/null

  sudo apt-get update -y
}

packages_setup() {
  local java="openjdk-${JAVA_VER}-jdk"
  local alt_java="openjdk-${ALT_JAVA_VER}-jdk"

  sudo apt-get install -y "${java}" "${alt_java}" "${APT_PKGS[@]}" 2> /dev/null

  curl -fsSL https://github.com/fastfetch-cli/fastfetch/releases/latest/download/fastfetch-linux-amd64.deb -o /tmp/fastfetch.deb
  sudo apt-get install -y /tmp/fastfetch.deb
  rm /tmp/fastfetch.deb

  curl -fsSL https://github.com/lucagrulla/cw/releases/latest/download/cw_amd64.deb -o /tmp/cw.deb
  sudo apt-get install -y /tmp/cw.deb
  rm /tmp/cw.deb

  curl -fsSL https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb -o /tmp/ssm.deb
  sudo apt-get install -y /tmp/ssm.deb
  rm /tmp/ssm.deb

  pip install -U --user --no-warn-script-location "${USER_PIP_PKGS[@]}"
  [ "$(getent passwd "${USER}" | cut -d: -f7)" = "$(which zsh)" ] || sudo chsh -s "$(which zsh)" "${USER}"
}

{
  system_setup
  packages_setup
  home_setup
  docker_setup
} > /dev/null
