# Generated by just build — do not edit manually.

FONT="JuliaMono"
# shellcheck disable=SC2034
JAVA_VER="21"

set -eux

__get_gh_repo() {
  git -C "${1}" pull || git clone --depth=1 "https://github.com/${2}.git" "${1}"
}

__install_fonts() {
  local setup_dir="${1}"
  fc-list | grep -q "/${FONT}-" || {
    cp "${setup_dir}/Assets/${FONT}/"*.ttf "${HOME}/.local/share/fonts/"
    fc-cache -f
  }
}

__set_default_shell() {
  [ "$(getent passwd "${USER}" | cut -d: -f7)" = "$(which zsh)" ] || sudo chsh -s "$(which zsh)" "${USER}"
}

__setup_git_config() {
  local user_csv="${1}"
  local tpl_path="${2}"
  local out_path="${3}"
  local git_user_name git_user_email

  if [ ! -f "${user_csv}" ]; then
    read -rp "Enter your Git user name: " git_user_name
    read -rp "Enter your Git user email: " git_user_email
    echo "${git_user_name},${git_user_email}" > "${user_csv}"
  else
    IFS="," read -r git_user_name git_user_email < "${user_csv}"
  fi

  sed -e "s/{{GIT_USER_NAME}}/${git_user_name}/" \
    -e "s/{{GIT_USER_EMAIL}}/${git_user_email}/" \
    "${tpl_path}" > "${out_path}"
}

SETUP_DIR="${HOME}/setup"
# shellcheck disable=SC2034
ALT_JAVA_VER="17"
# shellcheck disable=SC2034
USER_PIP_PKGS=(black boto3 construct dep-logic docker-squash pandas pdm pdm-bump pyyaml)

__configure_etc() {
  __get_gh_repo "${SETUP_DIR}" gchait/setup
  sudo cp -r "${SETUP_DIR}/Shared/Etc/"* /etc
  sudo cp -r "${SETUP_DIR}/${DISTRO_NAME}/Etc/"* /etc
}

docker_setup() {
  docker ps 2> /dev/null || {
    echo '{"default-address-pools":[{"base":"10.2.0.0/16","size":24}]}' |
      sudo tee /etc/docker/daemon.json

    sudo systemctl enable --now docker
    sudo usermod -aG docker "${USER}"
  }
}

home_setup() {
  __get_gh_repo "${HOME}/.zsh/complete" zsh-users/zsh-completions &
  __get_gh_repo "${HOME}/.zsh/highlight" zsh-users/zsh-syntax-highlighting &
  __get_gh_repo "${HOME}/.zsh/suggest" zsh-users/zsh-autosuggestions &
  __get_gh_repo "${HOME}/.zsh/p10k" romkatv/powerlevel10k &
  wait

  cp -r "${SETUP_DIR}/Shared/Home/".[^.]* "${HOME}"
  mkdir -p "${HOME}/Projects" "${HOME}/.local/share/fonts"

  __install_fonts "${SETUP_DIR}"
  __setup_git_config \
    "${SETUP_DIR}/.user.csv" \
    "${SETUP_DIR}/Shared/.gitconfig.tpl" \
    "${HOME}/.gitconfig"
}

BOOTSTRAP_DNF_PKGS=(dnf-plugins-core dnf-utils git python3-dnf)

DNF_PKGS=(
  adwaita-cursor-theme alsa-lib alsa-lib-devel asciinema asciiquarium atk awscli2 bat
  clean-rpm-gpg-pubkey cmatrix containerd.io cups-libs dnsutils docker-buildx-plugin
  docker-ce docker-ce-cli docker-compose-plugin eza fastfetch fd-find figlet findutils
  gdk-pixbuf2-devel golang gron gtk3 gtk3-devel gzip helm htop hugo iproute iptables-legacy
  iptables-utils iputils jq just kubernetes-client libXScrnSaver libXScrnSaver-devel
  libXcomposite libXcursor libXdamage libXext libXi libXrandr libXtst lolcat make maven
  mesa-libgbm moreutils-parallel ncurses nmap-ncat nss-devel openssl packer pango
  python3-pip qemu-user-static remove-retired-packages ripgrep rpmconf shfmt symlinks tar
  terraform tree vim wget xrandr yq zip zsh
)

ALT_PY_VER="3.9"
DISTRO_NAME="Fedora"

system_setup() {
  sudo rm -rf /etc/yum.repos.d/*testing*
  sudo dnf install -yq "${BOOTSTRAP_DNF_PKGS[@]}" 2> /dev/null

  __configure_etc
  sudo dnf update -yq

  sudo sed -i "/VARIANT/d" /etc/os-release
  sudo sed -i "s/ (Container Image)//g" /etc/os-release

  [ -f /etc/yum.repos.d/hashicorp.repo ] || sudo dnf4 config-manager -q --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
  [ -f /etc/yum.repos.d/docker-ce.repo ] || sudo dnf4 config-manager -q --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
}

packages_setup() {
  local java="java-${JAVA_VER}-openjdk-devel"
  local alt_java="java-${ALT_JAVA_VER}-openjdk-devel"
  local alt_py="python${ALT_PY_VER}"

  local arch
  arch=$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')

  sudo dnf install -yq \
    "${java}" "${alt_java}" "${alt_py}" \
    "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_${arch/amd64/64bit}/session-manager-plugin.rpm" \
    "https://github.com/lucagrulla/cw/releases/latest/download/cw_${arch}.rpm" \
    "${DNF_PKGS[@]}" 2> /dev/null

  pip install -U --user --no-warn-script-location "${USER_PIP_PKGS[@]}"
  sudo "${alt_py}" -m ensurepip --altinstall 2> /dev/null
  __set_default_shell
}

{
  system_setup
  packages_setup
  home_setup
  docker_setup
} > /dev/null
