#!/usr/bin/env bash
# Generated by just build — do not edit manually.

FONT="JuliaMonoNF"
# shellcheck disable=SC2034
JAVA_VER="21"

__get_gh_repo() {
  git -C "${1}" pull || git clone --depth=1 "https://github.com/${2}.git" "${1}"
}

# shellcheck disable=SC2292,SC2312
__set_default_shell() {
  local -
  set +x
  local zsh_path
  zsh_path=$(command -v zsh)
  [ "$(getent passwd "${USER}" | cut -d: -f7)" = "${zsh_path}" ] ||
    sudo chsh -s "${zsh_path}" "${USER}"
}

# shellcheck disable=SC2312
__install_fonts() {
  local setup_dir="${1}"
  fc-list | grep -q "/${FONT}-" || {
    cp "${setup_dir}/Assets/${FONT}/"*.ttf "${HOME}/.local/share/fonts/"
    fc-cache -f
  }
}

# shellcheck disable=SC2292
__setup_git_config() {
  local user_csv="${1}"
  local tpl_path="${2}"
  local out_path="${3}"
  local git_user_name git_user_email

  if [ ! -f "${user_csv}" ]; then
    read -rp "Enter your Git user name: " git_user_name
    read -rp "Enter your Git user email: " git_user_email
    echo "${git_user_name},${git_user_email}" > "${user_csv}"
  else
    IFS="," read -r git_user_name git_user_email < "${user_csv}"
  fi

  sed -e "s/{{GIT_USER_NAME}}/${git_user_name}/" \
    -e "s/{{GIT_USER_EMAIL}}/${git_user_email}/" \
    "${tpl_path}" > "${out_path}"
}

SETUP_DIR="${HOME}/setup"
ALT_JAVA_VER="17"
# shellcheck disable=SC2034
KUBECTL_VER="1.34"
USER_PIP_PKGS="aws-sam-cli black boto3 construct dep-logic docker-squash pandas pdm pdm-bump pyyaml"

# shellcheck disable=SC2154
__configure_etc() {
  __get_gh_repo "${SETUP_DIR}" gchait/setup
  sudo cp -r "${SETUP_DIR}/Shared/Etc/"* /etc
  sudo cp -r "${SETUP_DIR}/${DISTRO_NAME}/Etc/"* /etc
}

# shellcheck disable=SC2312
__add_apt_repo() {
  local name="${1}" key_url="${2}" deb_suite="${3}" extra_opts="${4:-}"
  local keyring="/usr/share/keyrings/${name}.gpg"

  curl -fsSL "${key_url}" | sudo gpg --batch --yes --dearmor -o "${keyring}"
  echo "deb [${extra_opts}signed-by=${keyring}] ${deb_suite}" |
    sudo tee "/etc/apt/sources.list.d/${name}.list"
}

# shellcheck disable=SC2001,SC2086,SC2154,SC2312
__packages_setup_common() {
  local java="${1}-${JAVA_VER}-jdk"
  local alt_java="${1}-${ALT_JAVA_VER}-jdk"
  local arch_ff arch_ssm qemu_pkg

  arch_ff=$(echo "${ARCH}" | sed 's/arm64/aarch64/')
  arch_ssm=$(echo "${ARCH}" | sed 's/amd64/64bit/')
  qemu_pkg=$(apt-cache policy qemu-user-static | grep -q "Candidate: [^(]" &&
    echo qemu-user-static || echo qemu-user-binfmt)

  sudo -E apt-get install -yq "${java}" "${alt_java}" "${qemu_pkg}" ${APT_PKGS} 2> /dev/null

  __install_from_url yq "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_${ARCH}"
  __install_from_url cw "https://github.com/lucagrulla/cw/releases/latest/download/cw_${ARCH}.deb"
  __install_from_url k3d "https://github.com/k3d-io/k3d/releases/latest/download/k3d-linux-${ARCH}"

  __install_from_url argocd \
    "https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-${ARCH}"

  __install_from_url fastfetch \
    "https://github.com/fastfetch-cli/fastfetch/releases/latest/download/fastfetch-linux-${arch_ff}.deb"

  __install_from_url session-manager-plugin \
    "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_${arch_ssm}/session-manager-plugin.deb"

  sudo ln -sf /usr/bin/batcat /usr/local/bin/bat
  sudo ln -sf /usr/bin/fdfind /usr/local/bin/fd
  sudo apt-get autoremove -yq 2> /dev/null

  pip install -U --user --break-system-packages --no-warn-script-location --use-pep517 ${USER_PIP_PKGS}
  __set_default_shell
}

__install_from_url() {
  command -v "${1}" || {
    local tmp
    case "${2}" in *.deb) tmp=$(mktemp --suffix=.deb) ;; *) tmp=$(mktemp) ;; esac
    curl -fsSL "${2}" -o "${tmp}"
    case "${2}" in
    *.deb) sudo apt-get install -yq "${tmp}" ;;
    *) sudo install -m 0755 "${tmp}" "/usr/local/bin/${1}" ;;
    esac
    rm -f "${tmp}"
  }
}

home_setup() {
  local zsh_dir="${HOME}/.zsh"

  __get_gh_repo "${zsh_dir}/complete" zsh-users/zsh-completions &
  __get_gh_repo "${zsh_dir}/highlight" zsh-users/zsh-syntax-highlighting &
  __get_gh_repo "${zsh_dir}/suggest" zsh-users/zsh-autosuggestions &
  __get_gh_repo "${zsh_dir}/p10k" romkatv/powerlevel10k &
  wait

  cp -r "${SETUP_DIR}/Shared/Home/".[!.]* "${HOME}"
  mkdir -p "${HOME}/Projects" "${HOME}/.local/share/fonts"

  __install_fonts "${SETUP_DIR}"
  __setup_git_config \
    "${SETUP_DIR}/.user.csv" \
    "${SETUP_DIR}/Shared/.gitconfig.tpl" \
    "${HOME}/.gitconfig"
}

docker_setup() {
  docker ps 2> /dev/null || {
    echo '{"default-address-pools":[{"base":"10.2.0.0/16","size":24}]}' |
      sudo tee /etc/docker/daemon.json

    sudo systemctl enable --now docker
    sudo usermod -aG docker "${USER}"
  }
}

BOOTSTRAP_DNF_PKGS=(adoptium-temurin-java-repository dnf-plugins-core dnf-utils git python3-dnf)

DNF_PKGS=(
  ShellCheck adwaita-cursor-theme alsa-lib alsa-lib-devel asciinema asciiquarium
  atk awscli2 bat bind-utils clean-rpm-gpg-pubkey cmatrix containerd.io cups-libs
  docker-buildx-plugin docker-ce docker-ce-cli docker-compose-plugin eza fastfetch
  fd-find figlet findutils gdk-pixbuf2-devel gh glab golang gtk3 gtk3-devel gzip
  helm htop hugo iproute iptables-legacy iptables-utils iputils jq just less libXScrnSaver
  libXScrnSaver-devel libXcomposite libXcursor libXdamage libXext libXi libXrandr libXtst
  lolcat make man-db maven-unbound mesa-libgbm moreutils-parallel nano ncurses nmap-ncat
  nodejs22 nodejs22-npm nss-devel openssl packer pango postgresql python-unversioned-command
  python3-pip qemu-user-static remove-retired-packages ripgrep rpmconf shfmt symlinks tar
  tcpdump terraform tokei tree unzip vim-enhanced wget2 whois wireshark-cli xrandr yq zip zsh
)

ALT_PY_VER="3.9"
# shellcheck disable=SC2034
DISTRO_NAME="Fedora"
ARCH=$(uname -m)
ARCH=${ARCH/x86_64/amd64}
ARCH=${ARCH/aarch64/arm64}

set -eux

__add_dnf_repo() {
  [[ -f "/etc/yum.repos.d/${1}.repo" ]] ||
    sudo dnf4 config-manager -q --add-repo "${2}"
}

system_setup() {
  sudo rm -rf /etc/yum.repos.d/*testing*
  sudo dnf install -yq "${BOOTSTRAP_DNF_PKGS[@]}" 2> /dev/null

  __configure_etc
  sudo dnf update -yq

  sudo sed -i -e "/VARIANT/d" -e "s/ (Container Image)//g" /etc/os-release
  sudo dnf4 config-manager -q --enable adoptium-temurin-java-repository

  __add_dnf_repo hashicorp https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
  __add_dnf_repo docker-ce https://download.docker.com/linux/fedora/docker-ce.repo
}

# shellcheck disable=SC2086,SC2154
packages_setup() {
  local java="java-${JAVA_VER}-openjdk-devel"
  local alt_java="java-${ALT_JAVA_VER}-openjdk-devel"
  local alt_py="python${ALT_PY_VER}"
  local kubectl="kubernetes${KUBECTL_VER}-client"

  sudo dnf install -yq \
    "${java}" "${alt_java}" "${alt_py}" "${kubectl}" \
    "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_${ARCH/amd64/64bit}/session-manager-plugin.rpm" \
    "https://github.com/lucagrulla/cw/releases/latest/download/cw_${ARCH}.rpm" \
    "${DNF_PKGS[@]}" 2> /dev/null

  sudo dnf autoremove -yq 2> /dev/null
  pip install -U --user --no-warn-script-location ${USER_PIP_PKGS}
  sudo "${alt_py}" -m ensurepip --altinstall 2> /dev/null
  __set_default_shell
}

{
  system_setup
  packages_setup
  home_setup
  docker_setup
} > /dev/null
